### ISSUE TITLE
Quick start guide does not work

### ISSUE THREAD

**Issue by bhaveshpraveen** [tanx-libs/tanx-connector-python#30]
Quick start guide references `stark_private_key` without initialising it. 

<img width="758" alt="Screenshot 2024-03-28 at 3 15 27 PM" src="https://github.com/tanx-libs/tanx-connector-python/assets/24614127/a8f98197-4a4e-4196-89ae-d3afef05519e">

**Comment by ayush-tanx** [comment]
This is working, Please make sure you are using the correct `ETH ADDRESS`, `PRIVATE KEY` and `STARK PRIVATE KEY` of the option (mainnet or testnet) you are trying to use.
![Screenshot from 2024-03-29 10-10-41](https://github.com/tanx-libs/tanx-connector-python/assets/160207723/adf3dbc7-2609-4617-bc9d-5370fc91fd5b)
